### ISSUE TITLE
Need jQuery

### ISSUE THREAD

**Issue by animate-object** [animate-object/is-ten#1]
It seems like we could do what we're already doing now, but with jQuery. 

I came across this plugin that adds basic math to jQuery:
https://github.com/cbrandolino/jQuery-basic-arithmetic-plugin

Would love some contributors to help get this milestone across.

**Comment by mattsp1290** [comment]
Really pushed this across the line for you.
[workaround for ant being a pile of fail](https://github.com/animate-object/is-ten/pull/2)

**Comment by animate-object** [comment]
This issue is resolved, thanks @mattsp1290
