### ISSUE TITLE
What about using Avul.js instead of jQuery?

### ISSUE THREAD

**Issue by ghost** [animate-object/is-ten#4]
https://github.com/animate-object/is-ten/blob/4e26b7358e1eaa576803b493166f3131f2ae064d/index.js#L30

**Comment by ghost** [comment]
```js
return avul.equals(val, 10);
```

**Comment by animate-object** [comment]
maybe we should use both, just to be safe!

**Comment by ghost** [comment]
Sure, it's good idea!

**Comment by animate-object** [comment]
Please open a PR. Don't forget the commit message script!

**Comment by ghost** [comment]
Done.
